
BBBB BBBBBBBBBBBB BBBB

BBBBBBBBBBBBBB BB BBBBBB

BB BBBBBB
XXXX gettext('Recent Tweets') XXXXX
XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
    BBB BBBBB BB BBBBBB
    XXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXFFFFFFFFFFFX XXXXXXX
        XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB
        XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBB
        XXXFFFFXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
         gettext('%(sometime)s ago') SSSSSSSSSSSS SSS
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
    XXXXX
    BBBBBB
XXXXX
BBBBB
