BBBB BBBBBBBBBB BBBB BBBBBBBBBBB

XXXX
    BBB BBBB BB BBBBBBBBBBB
    XXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXBBBBB BBBBBB BBBBBBXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                BB BBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX
            BBBBBBBBBBBBBBBBBBBB BBBB
            BB BBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBBB
            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBB BBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                XXXXXXXXXXXXXXXXXXXXXXX
            BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB
            XXXXX XXXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBBBBBBB
                XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            XXXXXXX
            BB BBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXX gettext('Add')  XXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBB
                    BBBBBBBBBBBBBBBBBBBBB BBBBB
                    BB BBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXX
                        XFFFFFFFFXXXXXXXXX
                    BBBBB
                BBBBBB
            XXXXXXXXX
            BBBBB

        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    XXXXX
    BBBBBB
XXXXX
