BBBB BBBB BBBBBBBBBB
BBBBBBBBB
BB BBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBB BB B
XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBB
    BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
    XXXBB BBBBBBB XXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBXX gettext('Home') XXXX
    XXXXX
    BBBBB
    BB BBBBBBBBBBBB
    XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
               BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX
        XXXXXX
        XX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BBBBBX
            
            BB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXBBBBB
        XXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    XXXXX
    BBBBB
    BBBBBB
XXXXX

BBBB
XXX XXXXXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBB
    BB BBBBBBBBBBBB
    XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBB
               BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX
        XXXXXX
        XX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    XXXXX
    BBBBB
    BBBBBB
XXXXX
BBBBB

BBBBB
BBBBBBBBBBBB
