BBBB BBBB BBBBBBBBBB

BBBBBBBBB
BB BBBBBBBBBBBBBBBBBBB

BBB BBBB BB BBBBBBBBBBB
    BB BBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXX
        BBBBB
    BBBBB

    BB BBBBBBBBBBBB
        BB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXX
        BBBBB
        XXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBB
            XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX
    BBBBB

    BB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB

    BB BBBBBBBBBBBB
        BB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBB
            XXXXXXXXXX
        BBBBB
    BBBBB

    BB BBBBBBBBBBBBBBB
        BB BBBBBBBBBBBB
            XXXXX
        BBBBB
        BB BBBBBBBBBBBB
            XXXXXX
        BBBBB
    BBBBB

BBBBBB

BBBBB
BBBBBBBBBBBB
