BBBB BBBB BBBBBBBBBB

BBBBBBBBB
BB BBBBBBBBBBB
BBB BBBB BB BBBBBBBBBBB

	BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
	XXX XXXXXXXXXXXXXXXXXXXX
		XXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBX
			   XXXXXXXXXXXXXXXXXXXX gettext('Home') XXXXXXXXX
    BBBBB

		BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
		BBBBB

		BB BBBBBBBBBBBBBBBBBBBBB
		XXX XXXXXXX
			BB BBBBBBBBBBBBB XXXXXBBBBB
			BB BBBBBBBBBBBB XXXXBBBBBX
			XXXXXXXXXXXXXXXXXX
			XX XXXXXXXXXXXX
		XXXXX
		BBBBB

	BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBB
	XXXXX
	BBBBB

BBBBBB
BBBBB
BBBBBBBBBBBB
