BBBBBBB BBBBBBBBBBB

BBBB BBBB

BBBBB BBBBBBBBBB
 gettext('Error') 
BBBBBBBB

BBBBB BBBBB
 gettext('Error') 
BBBBBBBB

BBBBB BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext('Error') XXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX gettext('Sorry, an error occurred.') XXXXXX
XXXXXX
BBBBBBBB
