BBBB BBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB

BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXBB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXBBBBBXX

    BBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
    BB BBB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBB
    XX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBBBBBBBB BBBBBBBBBBBBBXX
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    BBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBBBBBBBB BBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBB
            XXXXXX XXXXXXXXXXXXXXXXX
                 gettext('%(sometime)s ago') SSSSSSSSSSSS SSS
            XXXXXXXX
        XXXXX
    XXXFFFFFFFFFFFFFFXXXX
    BBBBB
    
    BB BBB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext('Link') 
    XXXX X
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext('Reply') 
    XXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX
    BBBBBBBBBB BBBBBBB
    XXXXXX
    BBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        BB BBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXBBBBBX
        BB BBBBBBBBBB BB BBBBBBBBBB
        BBBBBBBBBB BBBBBBBBBBBBBBBBBBB
        BBBB
        BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
        BBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Reply') XX
    XXXXXXX

    BBBB
    XXX
        BB BBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext('Comment deleted') 
        BBBB
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext('Comment awaiting approval') 
        BBBBB
        XXXXXX XXXXXXXXXXXXXXXXX gettext('%(sometime)s ago') SSSSSSSSSSSS SSSXXXXXXXX
    XXXX
    BBBBB

    BBBBBBBBBBBBBB BBBBBBB
    
    BB BBB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBB
    BBBBBBBBBBB
XXXXXX
BBBBBB

BB BBBBBBBBBBB
XXX gettext('There are currently no comments') XXXX
BBBBB

