BBBB BBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBBBBBBBBBBB
XXXXXXXX
    XXX XXXXXXXXXXXXXXXX X XX XX XXXXXXX
    XXX XXXXXXXXXX X XXXXXBB BBBBBBBBBBBBBBBBBXBBBBBXXXXX
    XXX XXXXXXXXXXXX X XFFFFFFFFXX
    XXX XXXXXXXXXXXXXXXXX X XBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBXX
  XXXXXXXXXXX X
   XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXX X XXXXX
   XXXXXXX X XXXXXBB BBBBBBBBBBBBBBBBBXBBBBBXXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXXXXXX
