BBBB BBBB


XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXBBB BBBBBBX XXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
    BBBBBBBBBB
    BBB BBBBB BB BBBBBBBBBBBBB
    XXBB BBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXBBBBBX
        XXX XX
        BB BBBBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB
    XXXX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Save') X XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext('Cancel') X XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
XXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXX gettext('Edit') XXXX


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
