BBBB BBBBBBBBBBBBBB BBBB
XXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext('Search') X XXXXXXXXXXX XXXXXXXX XXXXXXXXX
XXXXXX

BB BBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
    BBBB
    XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext('Everything') XXXXXXXXX
        BBB BBBBBBBBBBBBB BBBBB BB BBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXX
            BB BBBBB BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
            
        XXXXXXXXX
        BBBBBB
    XXXXXXXXX
    XXXXXX
    BBBBB
BBBBB

XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext('Go') XX

XXXXXXX
