BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBBB BBBBBBBB gettext('Blog') BBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB BBBB BB BBBBBBBB
BBB BBBBBBB BB BBBBBBBB
    BB BBB BBBBBBBBBBBBBX BBBBB
    
BBBBBB
BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB
BB BBBB
BBBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBB
 gettext('Blog') 
BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB

BB BBB BB BBBBBBBB BB BBBB BB BBBBB BB BBBBBB
XXXXBBBBBBBBB
BB BBB
     gettext('Tag:')  
BBBBBB BBBBBBBB
     gettext('Category:')  
BBBBBB BBBB BB BBBBB
    BB BBBBBX BBBBB
BBBBBB BBBBBB
     gettext('Author:')  FFFFFFFFFFFFFFFFFFFFFFF
BBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB
XXXXX
BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
BBBBBBBB
XXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBX BBBBBBBBXX
BBBBB BBBB

BB BBB BB BBBBBBBB BB BBBB BB BBBBB BB BBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXX
    BB BBB
         gettext('Viewing posts tagged')  
    BBBBBB BBBBBBBB
         gettext('Viewing posts for the category')  
    BBBBBB BBBB BB BBBBB
         gettext('Viewing posts from')  BB BBBBBX BBBBB
        
    BBBBBB BBBBBB
         gettext('Viewing posts by') 
        FFFFFFFFFFFFFFFFFFFFFFF
    BBBBBBBBBBBBBBBBBBBB
    BBBBBBBB
    XXXX
BBBB
    BB BBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        FFFFFFFFFFFFFFFFFFFF
        BBBBBBBBBBB
    BBBBB
    BBBBBBBB
    BBBBB
BBBBB

BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXX
XX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
XXXX
XXXX
BBBBBBBB
BBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBB

    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

BBBBBBBBBBB
BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBBBBBBBBB

	XXXXXXXX
     gettext('Posted by') X
    BBBB BBBBBBBBBBBBBB BB BBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXFFFFFFFFFFFFFFFFFFFFFFFXXXX
    BBBBBBB
    XXXXXXXXX
   X
    BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
    BB BBBBBBBBBB
     XXXXXXXX
     gettext('in') 
    BBB BBBBBBBB BB BBBBBBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXBB BBB BBBBBBBBBBBBX BBBBB
    BBBBBB
    X
    BBBBB
     XXXXXXXXX
     
    BBBBBBB
     XXXXXXXX
     gettext('%(sometime)s ago') SSSSSSSSSSSS SSS
     XXXXXXXXX
     X
       XXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBB
   
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBB BBBBBBBBBXX
         gettext('Comments') 
    XXXX
    BBBB
    XX XXXXXXXXXXXXXXXXX
         ngettext('%(comments_count)s comment', '%(comments_count)s comments', count) SSSSSSSSSSSSSSSSSS SSSSSSSPPPPPPPPPPPPPPPPPP PPPPPPPP
    XXXX
    BBBBB
    BBBBB
       XXXXXXXXX

BBBBBBBBBBB
BBBBBBBB



BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBBBB
FFFF
BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBBBB BBBBBBBBB BB BBBB
    BB BBBB
    XXX XXXXXXXXXXXXXXXXXX XXXXXX
     gettext('Tags') X
    BBBBBBBBB
    BBB BBB BB BBBB
    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
    BBBBBB
    BBBBBBBBBBBB
    XXXXX
    BBBBB
    XXX
    XX XXXXXXXX gettext('[read more]') XXXX
   
    XXXX
XXXXXX
BBBBBBBB

BBBBBB

BBBBBBBBBBBBBB BBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

BBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBBX BBBBBBBB XXXXXXXX
BBBBB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
XXXXXX
