XXXXXXXXX XXXXX
XXXXX XXXXXXXBB BBBBBBBBBBBBB XXXXXXXXXBBBBBX
BBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBBBBB

XXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB X BBBBBXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX

BBBBBBBBBBB BBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBXX
BBBBBBBBBBBBBB

BBBBBBBB BBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX


 XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
	
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX



XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBXX
BBBBB
BBBBBBBBBBB BBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
BB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
BBBBB
BBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBB
BBBBBBBBBBB

BBBBBBBB BB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBB BBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBB

XXXXXXX XX XX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXXXXXX

BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX

XXXXX XXXXBBBBB BBBBBBBXXXXXXXXBBBBBBBBXX
BBBBB BBBBB


BBBBBBBB
	XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX gettext('Toggle Navigation') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
    
    BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
XXXXXX
XXXXXX
BBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXX
	    XXXX XXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXX
				XXXXBBBBB BBBBBBBBBBBBBXXXXX
			XXXXXXXXXX XXXX XXX
	    XXXXXX XXXX XXXXXXXXXX XXX
	XXXXXX
BBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

BBBBBBBBBB
BB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX
BBB BBBBBBB BB BBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
XXXXXX
BBBBBB
XXXXXX
BBBBB
BBBBBBBBBBBBB

 
   



XXXXXX
BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX
XXXX XXXXXXXXXXXX
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBXBBBBBBBB XXXXXX
    BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXX
    BBBBBBBB
XXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBB X BBBBBBBBXXXXXXXX
    BBBBB BBBBBBBBBBBB
XXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXBBBBB BBBBBBBBBBBXBBBBBBBB XXXXXXX
    BBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBB
  
    BBBBB BBBBBBBBBBB
    BBBBBBBBBBB BBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBB
    BBBBBBBB
    
XXXXXX
BBBBBBBB

XXXXXX
XXXXXX
BBBBBBBB

XXXX XXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXXXX
	XXXX XXXXXXXXXXXXXXXXX
		 		BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB	
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXX
		 			XXXXXXXXXX XXXXXXXXXX
		 			XXXX XXXXXXXXXXXXXXXXXXXXXX
		 			XXX
		 				XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
		 				XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
		 				XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
		 				XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
		 				XX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
		 			XXXX
		 		XXXXXX
		 		XXXX XXXXXXXXXXXXXXXXX
		 			XXXXXXX XXXXXXXXXXX
		 			XXXX XXXXXXXXXXXXXXXXXXXXXX
		 			XXX
		 				XXXX XXXX XXXXXXXXX
		 				XXXXXX XXX XXXXXXXXXX
		 				XXXXXX XXXXXXXXXXXX
		 			XXXX
		 		XXXXXX
		 	
		XXXXXX

XXXX XXXXXXXXXXXX
XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
     gettext('Template by') 
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext('Mezzanine theme by') 
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
XXXX
XXXXXX
XXXXXX
XXXXXX
XXXX XXXX XXXXXXXXXX XXXXX XXX
  
    
     XXXX XXXXXX XX XXX XXX XX XXX XXXXXXXX XX XXX XXXXX XXXX XXXXXX XXX
   
   
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  	XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXX
  	    XXXXXXXX
XX XXXXXXXXX
XXXXXXXXXXXX X
	XXXX XXXXXXXX
	XXX XXXXXXXXXX X XXXXXXXXXXXXXXXX
		XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXX X XXXXXXXXXX
		
		XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
			XXXXXXXXXXXXXXX X XXXXXXXXXX
		X
				
		XXXXXXXXXXXXXXXXXXXX
			XXXXXXX XXXX
			XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
			XXXXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXX X
			XXXXXXXXX XXXX
			XXXXXXX XXXXXXXXX
			XXXXXX XXXXX
		XX
		XXXXXXXX X
		X
		XX XXXXXXXXXXXXXXXXXXXX
		
		XXXXXXXX XXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXXX X
			XX XXXXXX   
		X
				
		XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXX X
				XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXX
		XXX
		
		XXXXXXXX XXXXXXXXXXXXXXXXX X 
			XXX XXXXXXXX X XXXXXXXXXXXXXXXXXX 
			XXXXXXXXXXXX X XX
		
			XX XXXXXXXXX X XXXXX X
				XXXXXXXXXXXX X XX
			X XXXX XX XXXXXXXXX X XXXX X
				XXXXXXXXXXXX X XX
			X XXXX XX XXXXXXXXX X XXXX X
				XXXXXXXXXXXX X XX
			X XXXX XX XXXXXXXXX X XXXX X
				XXXXXXXXXXXX X XX
			X XXXX XX XXXXXXXXX X XXXX X
				XXXXXXXXXXXX X XX
			X
				XXXXXX XXXXXXXXXXXXX
			X       
			
			XXXXXXXX XXXXXXXXXXXX X
				XXX XXXXXXXX X XXXXXXXXXXXXXXXXXX 
				XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX 
				XXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
				
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X 
					XXXXXXXXXXXX X 
					XXXXX X XXXXXXXXX X XXXX 
				XXX
			XXX
		X
		
		XXXXXXXX XXXXXXXXXXXXXX X 
			XXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		X
			
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X 
			XXXXXXXXXXXXXXX
		XXX
		
		XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X 
		XXXXXXXXXXXXXXX          
	XXX
XXXXXXXXXXX
XXXXXXXXX

XXXXXXX
XXXXXXX
