BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBB
X XXX XXXXXXX XXX XXXX XXXXXX XX  XXXXXXXXX

 gettext('\nAt %(submit_date)s %(user_name)s wrote:\n') 
SS SSSSSSSSSSSSSSS SSSSSSSSSSSSS SSSSSS



BBBBBBBB
